defaults: &defaults
  working_directory: ~/workspace/repo
  docker:
    - image: circleci/node:9.10-alpine

to_persist: &to_persist
  root: ~/workspace
  paths:
    - repo/*

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          <<: *to_persist

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Lint JavaScript code
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Test service and generate coverage report
          command: |
            yarn test:coverage --ci
            yarn coveralls
      - persist_to_workspace:
          <<: *to_persist

workflows:
  version: 2
  default:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout